version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Atlantic/Canary
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Atlantic/Canary
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
    open-pull-requests-limit: 5
