// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unskip.Infrastructure.Persistence;

#nullable disable

namespace Unskip.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UnskipDbContext))]
    partial class UnskipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Unskip.Infrastructure.Persistence.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ipv4Address")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredDestination")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AliasKey")
                        .IsUnique();

                    b.HasIndex("ComputerName")
                        .IsUnique()
                        .HasFilter("\"ComputerName\" IS NOT NULL");

                    b.HasIndex("Ipv4Address")
                        .IsUnique()
                        .HasFilter("\"Ipv4Address\" IS NOT NULL");

                    b.ToTable("Devices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Devices_Destination", "\"ComputerName\" IS NOT NULL OR \"Ipv4Address\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Unskip.Infrastructure.Persistence.SendHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationSnapshot")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("SendHistoryRecords", (string)null);
                });

            modelBuilder.Entity("Unskip.Infrastructure.Persistence.SendHistoryEntity", b =>
                {
                    b.HasOne("Unskip.Infrastructure.Persistence.DeviceEntity", "Device")
                        .WithMany("SendHistoryRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Unskip.Infrastructure.Persistence.DeviceEntity", b =>
                {
                    b.Navigation("SendHistoryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
